# Generated by Django 3.2.4 on 2021-06-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='techs',
        ),
        migrations.AddField(
            model_name='project',
            name='techs',
            field=models.ManyToManyField(related_name='project_techs', to='page.Tech'),
        ),
        migrations.AddField(
            model_name='job',
            name='techs',
            field=models.ManyToManyField(related_name='job_techs', to='page.Tech'),
        ),
    ]
